### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by jcowgar** [typhonjs-node-esdoc/esdoc-plugin-enhanced-navigation#2]
Once I got the plugin up and running by copying in the templates directory, I now get:

```
➜  dragon-js ./node_modules/.bin/esdoc -c esdoc.json                                                                                      (feature/esdoc|✚1…)
/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc/out/src/Plugin/Plugin.js:94
            throw _iteratorError;
            ^

TypeError: Cannot read property 'type' of undefined
    at EnhancedNavDocBuilder._createSCMLink (/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc-plugin-enhanced-navigation/dist/EnhancedNavDocBuilder.js:337:29)
    at /Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc-plugin-enhanced-navigation/dist/EnhancedNavDocBuilder.js:433:32
    at Array.forEach (native)
    at EnhancedNavDocBuilder._filterLocalDocs (/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc-plugin-enhanced-navigation/dist/EnhancedNavDocBuilder.js:411:20)
    at EnhancedNavDocBuilder.buildNavDoc (/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc-plugin-enhanced-navigation/dist/EnhancedNavDocBuilder.js:195:15)
    at Object.onHandleTag (/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc-plugin-enhanced-navigation/dist/plugin.js:72:91)
    at Plugin._execHandler (/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc/out/src/Plugin/Plugin.js:82:30)
    at Plugin.onHandleTag (/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc/out/src/Plugin/Plugin.js:172:12)
    at Function.generate (/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc/out/src/ESDoc.js:202:45)
    at ESDocCLI.exec (/Users/jeremy/Projects/AMPS/dragon-js/node_modules/esdoc/out/src/ESDocCLI.js:90:28)
```

My packages.json (relevant parts) include:

```
"devDependencies": {
    "esdoc": "0.4.7",
    "esdoc-es7-plugin": "0.0.3",
    "esdoc-plugin-enhanced-navigation": "0.0.3",
    "esdoc-plugin-jspm": "^0.6.0",
    "jspm": "^0.16.0"
}
```

and my esdoc.json:

```
{
    "source": "./src",
    "destination": "./esdoc",
    "plugins": [
        {
            "name": "esdoc-es7-plugin"
        },
        {
            "name": "esdoc-plugin-enhanced-navigation"
        }
    ]
}
```

**Comment by typhonrt** [comment]
This should be fixed now as it likely was a sanity checking issue with any missing repository details in related `package.json` files. Let me know if 0.0.5 solves the issue. :D

**Comment by jcowgar** [comment]
That did the trick, it's now a much better navigation menu! Thanks a lot for this plugin!

**Comment by typhonrt** [comment]
Excellent, if you are using Github consider adding a `repository` field in your `package.json` file [like](https://docs.npmjs.com/files/package.json#repository): 

```
{
   ...
   "repository" :
   { 
      "type" : "git",
      "url" : "https://github.com/<user or organization name>/<repo name>.git"
   }
}
```

and that will take things up a notch adding Github linking for the packages / directories / folders / files / docs, etc. IE each one of your exported functions would jump to the correct line / Github source given docs generated during CI, etc. Presently only Github is supported in this regard, but more SCM platforms could be added on request..
